/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const IconData arrow_left = const IconData(0xe879, fontFamily: _kFontFam);
  static const IconData arrow_right = const IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData bubble_chart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData car = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData drop = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData drop_1 = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData drop_2 = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData droplet = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData envira = const IconData(0xf299, fontFamily: _kFontFam);
  static const IconData feather = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData feather_1 = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData garden = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData github_circled_alt2 = const IconData(0xf056, fontFamily: _kFontFam);
  static const IconData growth = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData icons8_moisture_50 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData invert_colors = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData leaf = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData leaf_1 = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData leaf_2 = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData leaf_3 = const IconData(0xe849, fontFamily: _kFontFam);
  static const IconData local_florist = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData opacity = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData pagelines = const IconData(0xf18c, fontFamily: _kFontFam);
  static const IconData pitcher = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData plus = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData plus_outline = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData soil_moisture = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData spa = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData time = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData tint = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData tint_1 = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData toys = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData tree_1 = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData tree_2 = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData user_1 = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData user_2 = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData water = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData water_1 = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData water_tank = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData wi_humidity = const IconData(0xe803, fontFamily: _kFontFam);

  static const _kFontFam = 'CustomIcons';
}
