/// Flutter icons MonopolyIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MonopolyIcon
///      fonts:
///       - asset: fonts/MonopolyIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MonopolyIcon {
  MonopolyIcon._();

  static const IconData dollar =
      const IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

  static const _kFontFam = 'MonopolyIcon';
  static const _kFontPkg = null;
}
